import type { Metadata } from "next";
import { Outfit, Young_Serif } from "next/font/google";

const outfit = Outfit({ 
    subsets: ["latin"], 
    display: 'swap',
    variable: '--font-outfit',
});

const ys = Young_Serif({ 
    subsets: ["latin"], 
    display: 'swap',
    weight: '400',
    variable: '--font-ys',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${ys.variable}`}>{children}</body>
    </html>
  );
}
