import type { Metadata } from "next";
import { 
  Poppins,
  Montserrat, 
  Fraunces, 
  Outfit, 
  Young_Serif  
} from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"], 
  display: 'swap',
  variable: '--font-poppins',
  weight: ['300','600']
})

const montserrat = Montserrat({ 
  subsets: ["latin"], 
  display: 'swap',
  variable: '--font-montserrat',
  weight: ['500', '700']
});

const fraunces = Fraunces({ 
  subsets: ["latin"], 
  display: 'swap',
  weight: '700',
  variable: '--font-fraunces',
});

const outfit = Outfit({ 
  subsets: ["latin"], 
  display: 'swap',
  variable: '--font-outfit',
});

const ys = Young_Serif({ 
  subsets: ["latin"], 
  display: 'swap',
  weight: '400',
  variable: '--font-ys',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${montserrat.variable} ${fraunces.variable} ${outfit.variable} ${ys.variable}`}>{children}</body>
    </html>
  );
}
